micronaut:
  application:
    name: tour
    router:
      static-resources:
        swagger:
          paths: classpath:META-INF/swagger
          mapping: /swagger/**
cassandra:
  default:
    basic:
      contact-points:
         - localhost:9042
      session-keyspace: mykeyspace
      load-balancing-policy:
        local-datacenter: datacenter1

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
