micronaut:
  application:
    name: tour
    router:
      static-resources:
        swagger:
          paths: classpath:META-INF/swagger
          mapping: /swagger/**
cassandra:
  default:
    basic:
      contact-points:
        - 127.0.0.1:9042
      session-keyspace: travel
      load-balancing-policy:
        local-datacenter: datacenter1
nats:
  addresses:
    - "nats://localhost:4222"